name: SofkaFinance

networks:
  backend:
    driver: bridge
  database:
    driver: bridge

services:
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks: [backend]

  customers.api:
    build:
      context: ./src/Services/Customers
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      RabbitMQ__Host: rabbitmq
      RabbitMQ__User: ${RABBITMQ_USER}
      RabbitMQ__Password: ${RABBITMQ_PASS}
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks: [backend]

  accounts.api:
    build:
      context: ./src/Services/Account
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      RabbitMQ__Host: rabbitmq
      RabbitMQ__User: ${RABBITMQ_USER}
      RabbitMQ__Password: ${RABBITMQ_PASS}
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks: [backend]

  gateway:
    build:
      context: ./src/ApiGateway
      dockerfile: Dockerfile
    ports:
      - "${GATEWAY_PORT}:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      RabbitMQ__Host: rabbitmq
      RabbitMQ__User: ${RABBITMQ_USER}
      RabbitMQ__Password: ${RABBITMQ_PASS}
    depends_on:
      customers.api:
        condition: service_started
      accounts.api:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    networks: [backend]

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest # Licencia permitida en desarrollo
    container_name: sqlserver
    ports:
      - "${MSSQL_PORT}:1433"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "${MSSQL_SA_PASSWORD}"
    volumes:
      - sqlserver-data:/var/opt/mssql
    restart: always
    networks: [database]

volumes:
  sqlserver-data:
